### ISSUE TITLE
Blurb not showing up

### ISSUE THREAD

**Issue by WiBla** [ExtPlug/rollover-blurb#1]
I get this error when clicking a rollover :
![chrome_2016-09-04_11-39-07](https://cloud.githubusercontent.com/assets/11421812/18230195/5ca61922-7294-11e6-848f-cff3c8a2fb48.png)

In case image is not showing up:

> "request is not a function"

Line 52 in rollover-blurb.js

**Comment by goto-bus-stop** [comment]
Oh! Looks like I made a mistake upgrading ExtPlug core to Babel 6. Should be fixed in ExtPlug v0.16.2, thanks for the report :)

**Comment by WiBla** [comment]
Thanks for the fast fix !
